### ISSUE TITLE
Disabling upload to Data directory

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#144]
1) Disable the Workspace folder from the dashboard, since there is no backend support
2) Disable uploading to the Data directory, since it should only refer to data exposed via the catalog.

This will need to happen both in the current UI and the new UI.

**Comment by abrinckm** [comment]
resolved in commit [9b3c6b49](https://github.com/whole-tale/dashboard/commit/9b3c6b491a4488da682b8fe2ea4f09b7385168b8)

**Comment by Xarthisius** [comment]
I tried applying that on stable branch:

```diff --git a/Dockerfile b/Dockerfile
index f85f89d..6b85175 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -21,7 +21,7 @@ RUN bower install --allow-root
 RUN ./node_modules/.bin/ember build --environment=production
 
 FROM nginx:stable-alpine
-ENV GIRDER_API_URL=https://girder.prod.wholetale.org
+ENV GIRDER_API_URL=https://girder.dev.wholetale.org
 COPY --from=builder /usr/src/node-app/dist /srv/dashboard/.
 COPY ./nginx.conf /etc/nginx/conf.d/default.conf
 COPY ./docker-entrypoint.sh /
diff --git a/app/components/folder-navigator/template.hbs b/app/components/folder-navigator/template.hbs
index 800d7ec..1f4dc1d 100644
--- a/app/components/folder-navigator/template.hbs
+++ b/app/components/folder-navigator/template.hbs
@@ -2,18 +2,17 @@
     <div class="sixteen wide tablet computer only column">
         <div class="ui vertical mini labeled compact icon menu">
           {{#each navs as |nav|}}
-            {{#if (eq currentNavCommand nav.command)}}
+            {{#if (and (eq currentNavCommand nav.command) nav.allowUpload)}}
                 <a class="active item" {{action "navClicked" nav}}>
                     <i class="{{nav.icon}} icon"></i>
                     {{nav.name}}
                 </a>
-            {{/if}}
-            {{#unless (eq currentNavCommand nav.command)}}
+            {{else}}
                 <a class="item" {{action "navClicked" nav}}>
                     <i class="{{nav.icon}} icon"></i>
                   {{nav.name}}
                 </a>
-            {{/unless}}
+            {{/if}}
           {{/each}}
         </div>
     </div>
diff --git a/app/services/folder-navs.js b/app/services/folder-navs.js
index 1486025..65b8b68 100644
--- a/app/services/folder-navs.js
+++ b/app/services/folder-navs.js
@@ -16,7 +16,8 @@ export default Ember.Service.extend({
         parentId: thisUserID,
         parentType : "user",
         icon : "home",
-        isFolder :  true
+        isFolder :  true,
+        allowUpload: true
       },
       {
         name : "Data",
@@ -24,7 +25,8 @@ export default Ember.Service.extend({
         parentId : thisUserID,
         parentType : "user",
         icon : "file",
-        isFolder :  true
+        isFolder :  true,
+        allowUpload: false
       },
       {
         name : "Workspace",
@@ -32,7 +34,8 @@ export default Ember.Service.extend({
         parentId : thisUserID,          //TODO: Find out what the parent is
         parentType : "user",
         icon : "folder",
-        isFolder :  true                //TODO: Find out whether this is an actual folder
+        isFolder :  true,               //TODO: Find out whether this is an actual folder
+        allowUpload: false
       },
       {
         name : "Recent",
@@ -40,7 +43,8 @@ export default Ember.Service.extend({
         parentId : null,
         parentType : null,
         icon : "calendar",
-        isFolder :  false
+        isFolder :  false,
+        allowUpload: false
       }
 
     ];
```

but it still shows me the "upload button".

**Comment by abrinckm** [comment]
Ah. If you want to apply to stable without fully merging the newui, then there is one more change needed. However, the particular file that needs changed doesn't exist on stable yet. Let me look and see if I can patch it.

**Comment by abrinckm** [comment]
Okay, so since the new ui is vastly different, I can't merge the proper fix.
But I did a hack on stable branch that resolves this issue

**Comment by craig-willis** [comment]
@abrinckm I've deployed the change to staging (https://dashboard.stage.wholetale.org/), and uploading to the data directory is disabled. However, the Workspace folder is still enabled (first bullet in issue).

**Comment by abrinckm** [comment]
Removed the Workspace folder [6a0665a](https://github.com/whole-tale/dashboard/commit/6a0665aed78b75be929a81963935af77dc01c9c6)
