### ISSUE TITLE
Incorrect Behavior on Tale Close

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#155]
When clicking the black `X` next to the tale name in the `Launched Tales` widget in the `Browse` page, a redirect to /run/id happens and a backdrop appears like a modal is expected.

To Reproduce,
1. Navigate to https://newdashboard.dev.wholetale.org/browse
2. You need at least one tale launched, so launch one if you need to
3. Still on the browse page, find your tale in the `Launched Tales` widget
4. Click the `X` to close the tale
5. Experience the unexpected behavior

<img width="844" alt="screen shot 2018-06-25 at 5 13 44 pm" src="https://user-images.githubusercontent.com/9289652/41881982-37152b1c-789b-11e8-8557-70756d93c649.png">

**Comment by cyberdante** [comment]
Actually, that button does NOT close the tale instance but deletes it. Maybe is not too intuitive but that's what we have across the web app.

**Comment by cyberdante** [comment]
@Tommy, could you please verify this is now fixed? Thanks beforehand

**Comment by ThomasThelen** [comment]
I still see it happening when I'm on the `Browse` page. When doing it on the `Run` page, it works fine.

Tested in Build: `7199664`

**Comment by cyberdante** [comment]
Could you please retry now, @ThomasThelen? There is a new version/build *5c50955* of the `newdashboard`

**Comment by ThomasThelen** [comment]
Tested with `5c50955` and it looks good to me!
